version: '3'
services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
  nginx:
    image: nginx:latest
    ports:
      - "3000:80"
    volumes:
      - ./app/src/main/resources/index.html:/usr/share/nginx/html/index.html
      - ./app/target/scala-2.13/zio-project-playground-app-fastopt.js:/usr/share/nginx/html/zio-project-playground-app-fastopt.js
      - ./nginx.conf:/etc/nginx/conf.d/default.conf